[project]
name = "txt2cql"
version = "0.0.1"
description = "Convert input text into a valid Centreon Query Language request"
authors = [{ name = "Denis Roussel", email = "droussel@centreon.com" }]
requires-python = "~=3.11"
readme = "README.md"
dependencies = [
    "pyperclip>=1,<2",
    "openai>=1,<2",
    "typer>=0,<1",
    "rich>=13,<14",
]

[project.scripts]
txt2cql = "txt2cql.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
